version: "3.8"

services:
  db:
    env_file:
        - "./.env"
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '9525:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
        - server
  app:
    env_file:
      - "./.env"
    image: advertising
    container_name: app
    build: .
    ports: 
      - 9528:8080 
    restart: on-failure
    depends_on:
      - db    
    networks:
      - server
volumes:
  db:  
networks:
  server:
 